/**
 * ejercicios-extra.js — Ampliación masiva de la librería de ejercicios.
 * Empuja a EJS todos los que no existan ya (dedupe por nombre normalizado).
 * Grupos: usan GRUPOS existentes. Equipos: usan EQUIPOS existentes
 * (Landmine/Trap/Suiza -> Barra; TRX/Fitball -> Peso corporal).
 */
(function () {
  if (typeof EJS === "undefined") return;
  var L = [
    // ================= PECHO =================
    ["Press de Banca Plano con Barra","Pecho","Barra","Pectoral mayor, tríceps, hombro anterior","c"],
    ["Press Declinado con Barra","Pecho","Barra","Pectoral inferior, tríceps","c"],
    ["Press Plano con Mancuernas","Pecho","Mancuernas","Pectoral mayor, tríceps","c"],
    ["Press Plano en Máquina Smith","Pecho","Smith","Pectoral mayor, tríceps","c"],
    ["Press Inclinado en Máquina Smith","Pecho","Smith","Pectoral superior, tríceps","c"],
    ["Press Declinado en Máquina Smith","Pecho","Smith","Pectoral inferior, tríceps","c"],
    ["Press Inclinado en Máquina Hammer","Pecho","Máquina","Pectoral superior, tríceps","c"],
    ["Press Declinado en Máquina Hammer","Pecho","Máquina","Pectoral inferior, tríceps","c"],
    ["Press Sentado en Máquina de Placas","Pecho","Máquina","Pectoral mayor, tríceps","c"],
    ["Flexiones con Chaleco Lastrado","Pecho","Peso corporal","Pectoral, tríceps, core","c"],
    ["Flexiones con Agarre Ancho","Pecho","Peso corporal","Pectoral, hombro","c"],
    ["Flexiones Pliométricas con Palmada","Pecho","Peso corporal","Pectoral, tríceps (potencia)","c"],
    ["Flexiones Spiderman","Pecho","Peso corporal","Pectoral, core, oblicuos","c"],
    ["Flexiones sobre Balones Medicinales","Pecho","Peso corporal","Pectoral, estabilizadores","c"],
    ["Flexiones con Bandas de Resistencia","Pecho","Banda","Pectoral, tríceps","c"],
    ["Flexiones Esfinge","Pecho","Peso corporal","Tríceps, pectoral","c"],
    ["Fondos en Anillas","Pecho","Peso corporal","Pectoral inferior, tríceps, estabilizadores","c"],
    ["Fondos con Lastre","Pecho","Peso corporal","Pectoral inferior, tríceps","c"],
    ["Press Svend con Dos Discos","Pecho","Disco","Pectoral interno","a"],
    ["Press Hex con Mancuernas en Banco Plano","Pecho","Mancuernas","Pectoral interno, tríceps","c"],
    ["Press Hex con Mancuernas en Banco Inclinado","Pecho","Mancuernas","Pectoral superior interno","c"],
    ["Press de Pecho con Barra Landmine a Dos Manos","Pecho","Barra","Pectoral superior, hombro","c"],
    ["Press de Pecho con Barra Landmine a Una Mano","Pecho","Barra","Pectoral superior, hombro, core","c"],
    ["Press de Banca Agarre Neutro con Barra Suiza","Pecho","Barra","Pectoral, tríceps","c"],
    ["Press de Banca Agarre Invertido","Pecho","Barra","Pectoral superior, tríceps","c"],
    ["Press de Pecho Guiado en Polea de Pie","Pecho","Polea","Pectoral mayor","c"],
    ["Aperturas con Mancuernas y Agarre Prono","Pecho","Mancuernas","Pectoral mayor","a"],
    ["Cruce de Poleas Altas","Pecho","Polea","Pectoral inferior","a"],
    ["Cruce de Poleas Medias","Pecho","Polea","Pectoral mayor","a"],
    ["Cruce de Poleas Bajas","Pecho","Polea","Pectoral superior","a"],
    ["Cruce de Poleas Sentado","Pecho","Polea","Pectoral mayor","a"],
    ["Cruce de Poleas Acostado en Banco Plano","Pecho","Polea","Pectoral mayor","a"],
    ["Cruce de Poleas Acostado en Banco Inclinado","Pecho","Polea","Pectoral superior","a"],
    ["Cruce de Poleas a Una Mano","Pecho","Polea","Pectoral mayor","a"],
    ["Pec Deck con Agarre Neutro","Pecho","Máquina","Pectoral mayor","a"],
    ["Aperturas en Polea con Manijas en Banco Plano","Pecho","Polea","Pectoral mayor","a"],
    ["Aperturas en Polea con Manijas en Banco Inclinado","Pecho","Polea","Pectoral superior","a"],
    ["Aperturas en TRX / Suspensión","Pecho","Peso corporal","Pectoral, core","a"],
    ["Aperturas con Discos en Suelo (Deslizantes)","Pecho","Disco","Pectoral, core","a"],
    ["Pullover con Barra Z en Banco","Pecho","Barra","Pectoral, dorsal, serrato","a"],
    ["Pullover en Polea Alta con Cuerda","Pecho","Polea","Dorsal, pectoral","a"],
    ["Pullover en Máquina Específica","Pecho","Máquina","Dorsal ancho, pectoral","a"],
    ["Press Inclinado con Agarre Supino","Pecho","Barra","Pectoral superior","c"],
    ["Press de Banca Unilateral con Mancuerna","Pecho","Mancuernas","Pectoral, core","c"],
    ["Press Inclinado Unilateral con Mancuerna","Pecho","Mancuernas","Pectoral superior, core","c"],
    ["Flexiones con Déficit","Pecho","Peso corporal","Pectoral, tríceps","c"],
    ["Flexiones Pseudo Plancha","Pecho","Peso corporal","Pectoral superior, hombro","c"],
    ["Press de Banca con Pausa","Pecho","Barra","Pectoral, tríceps","c"],
    ["Press de Banca Spoto","Pecho","Barra","Pectoral, tríceps","c"],
    ["Press de Banca con Cadenas","Pecho","Barra","Pectoral, tríceps","c"],
    ["Press de Banca con Bandas Elásticas","Pecho","Banda","Pectoral, tríceps","c"],
    ["Floor Press con Mancuernas","Pecho","Mancuernas","Pectoral, tríceps","c"],
    ["Pin Press Plano en Rack","Pecho","Barra","Pectoral, tríceps","c"],
    ["Pin Press Inclinado en Rack","Pecho","Barra","Pectoral superior, tríceps","c"],
    ["Press Svend en Polea Baja","Pecho","Polea","Pectoral interno","a"],

    // ================= ESPALDA =================
    ["Dominadas con Agarre Prono Neutro","Espalda","Peso corporal","Dorsal, bíceps, braquial","c"],
    ["Dominadas con Agarre Mixto","Espalda","Peso corporal","Dorsal, bíceps","c"],
    ["Dominadas con Lastre","Espalda","Peso corporal","Dorsal, bíceps","c"],
    ["Dominadas con Agarre en Toalla","Espalda","Peso corporal","Dorsal, antebrazo, agarre","c"],
    ["Dominadas tipo Commando","Espalda","Peso corporal","Dorsal, bíceps, core","c"],
    ["Dominadas Arqueras","Espalda","Peso corporal","Dorsal (unilateral), bíceps","c"],
    ["Dominadas Trasnuca","Espalda","Peso corporal","Dorsal, romboides","c"],
    ["Jalón al Pecho con Agarre Neutro Ancho","Espalda","Polea","Dorsal, braquial","c"],
    ["Jalón al Pecho con Agarre Neutro Estrecho (V-bar)","Espalda","Polea","Dorsal, bíceps","c"],
    ["Jalón al Pecho con Barra Z","Espalda","Polea","Dorsal, bíceps","c"],
    ["Jalón Trasnuca en Polea","Espalda","Polea","Dorsal, romboides","c"],
    ["Jalón al Pecho en Máquina Articulada Hammer","Espalda","Máquina","Dorsal ancho, bíceps","c"],
    ["Jalón Unilateral en Máquina Hammer","Espalda","Máquina","Dorsal (unilateral)","c"],
    ["Jalón al Pecho Cruzado con Dos Poleas","Espalda","Polea","Dorsal ancho","c"],
    ["Remo con Barra Inclinado Agarre Supino","Espalda","Barra","Dorsal, bíceps","c"],
    ["Remo con Mancuerna a Una Mano sin Apoyo","Espalda","Mancuernas","Dorsal, romboides, core","c"],
    ["Remo con Mancuernas Simultáneo en Banco Inclinado","Espalda","Mancuernas","Dorsal, trapecio medio","c"],
    ["Remo Seal con Barra en Banco Elevado","Espalda","Barra","Dorsal, romboides","c"],
    ["Remo Seal con Mancuernas","Espalda","Mancuernas","Dorsal, romboides","c"],
    ["Remo en Barra T Apoyado en Pecho","Espalda","Barra","Dorsal, trapecio medio","c"],
    ["Remo Sentado en Polea Baja Agarre V","Espalda","Polea","Dorsal, romboides","c"],
    ["Remo Sentado en Polea Baja Agarre Ancho Prono","Espalda","Polea","Dorsal, trapecio, deltoide posterior","c"],
    ["Remo Sentado en Polea Baja Agarre Ancho Supino","Espalda","Polea","Dorsal, bíceps","c"],
    ["Remo Sentado en Polea Baja Unilateral","Espalda","Polea","Dorsal (unilateral)","c"],
    ["Remo Sentado en Polea Baja con Cuerda","Espalda","Polea","Dorsal, romboides","c"],
    ["Remo en Máquina Articulada Hammer Bilateral","Espalda","Máquina","Dorsal, romboides","c"],
    ["Remo en Máquina Articulada Hammer Unilateral","Espalda","Máquina","Dorsal (unilateral)","c"],
    ["Remo Meadow con Barra Landmine","Espalda","Barra","Dorsal, trapecio","c"],
    ["Remo Kroc con Mancuerna Pesada","Espalda","Mancuernas","Dorsal, trapecio, agarre","c"],
    ["Remo Yates con Barra","Espalda","Barra","Dorsal, trapecio","c"],
    ["Remo Dorian con Agarre Supino","Espalda","Barra","Dorsal, bíceps","c"],
    ["Remo con Barra Landmine a Dos Manos con Agarre V","Espalda","Barra","Dorsal, romboides","c"],
    ["Remo Australiano / Invertido en Barra","Espalda","Peso corporal","Dorsal, romboides, core","c"],
    ["Pullover en Polea Alta con Barra V","Espalda","Polea","Dorsal ancho","a"],
    ["Pullover Unilateral en Polea","Espalda","Polea","Dorsal (unilateral)","a"],
    ["Face Pull Sentado en Polea","Espalda","Polea","Deltoide posterior, trapecio","a"],
    ["Face Pull con Bandas Elásticas","Espalda","Banda","Deltoide posterior, romboides","a"],
    ["Encogimientos con Barra por Delante","Espalda","Barra","Trapecio superior","a"],
    ["Encogimientos con Barra por Detrás","Espalda","Barra","Trapecio superior","a"],
    ["Encogimientos en Máquina Smith","Espalda","Smith","Trapecio superior","a"],
    ["Encogimientos en Máquina de Discos","Espalda","Máquina","Trapecio superior","a"],
    ["Encogimientos en Polea Baja","Espalda","Polea","Trapecio superior","a"],
    ["Encogimientos en Banco Inclinado con Mancuernas","Espalda","Mancuernas","Trapecio medio","a"],
    ["Hiperextensiones en Banco 45°","Espalda","Peso corporal","Espalda baja, glúteo, femoral","c"],
    ["Extensiones Lumbares Horizontales en Banco","Espalda","Peso corporal","Espalda baja, glúteo","c"],
    ["Extensiones Lumbares con Disco","Espalda","Disco","Espalda baja, glúteo","c"],
    ["Good Mornings en Máquina Smith","Espalda","Smith","Femoral, glúteo, espalda baja","c"],
    ["Good Mornings con Banda de Resistencia","Espalda","Banda","Femoral, glúteo, espalda baja","c"],
    ["Rack Pulls por Encima de las Rodillas","Espalda","Barra","Trapecio, dorsal, glúteo","c"],
    ["Rack Pulls por Debajo de las Rodillas","Espalda","Barra","Espalda baja, glúteo, trapecio","c"],
    ["Jefferson Curl con Pesas","Espalda","Mancuernas","Espalda baja, femoral","a"],
    ["Bird-Dog para Zona Lumbar","Espalda","Peso corporal","Espalda baja, core, glúteo","a"],
    ["Supermán en Suelo","Espalda","Peso corporal","Espalda baja, glúteo","a"],
    ["Remo con Barra Agarre Ultra Ancho","Espalda","Barra","Dorsal, deltoide posterior, trapecio","c"],
    ["Remo Horizontal en Máquina de Placas","Espalda","Máquina","Dorsal, romboides","c"],
    ["Remo Inclinado con Mancuernas Agarre Neutro","Espalda","Mancuernas","Dorsal, trapecio medio","c"],
    ["Remo en Polea con Manijas Individuales","Espalda","Polea","Dorsal, romboides","c"],
    ["Jalón Unilateral Supino en Polea","Espalda","Polea","Dorsal, bíceps","c"],
    ["Dominadas en Barra Gruesa (Fat Gripz)","Espalda","Peso corporal","Dorsal, agarre, antebrazo","c"],
    ["Remo con Barra Landmine Lateral","Espalda","Barra","Dorsal, oblicuos","c"],
    ["Encogimientos Haney con Barra tras la Espalda","Espalda","Barra","Trapecio superior","a"],

    // ================= HOMBRO =================
    ["Press Militar Sentado con Barra por Delante","Hombro","Barra","Deltoide anterior/medio, tríceps","c"],
    ["Press Trasnuca con Barra","Hombro","Barra","Deltoide medio, tríceps","c"],
    ["Press Sentado con Mancuernas Agarre Prono","Hombro","Mancuernas","Deltoide anterior/medio, tríceps","c"],
    ["Press Sentado con Mancuernas Agarre Neutro","Hombro","Mancuernas","Deltoide anterior, tríceps","c"],
    ["Press de Hombros en Máquina Smith","Hombro","Smith","Deltoide anterior/medio, tríceps","c"],
    ["Press Trasnuca en Máquina Smith","Hombro","Smith","Deltoide medio, tríceps","c"],
    ["Press de Hombros en Máquina Articulada Hammer","Hombro","Máquina","Deltoide, tríceps","c"],
    ["Press de Hombros en Máquina de Placas","Hombro","Máquina","Deltoide, tríceps","c"],
    ["Push Press con Barra","Hombro","Barra","Deltoide, tríceps, pierna","c"],
    ["Press Jerk de Hombros","Hombro","Barra","Deltoide, tríceps, pierna","c"],
    ["Press de Hombros Unilateral con Mancuerna de Pie","Hombro","Mancuernas","Deltoide, core","c"],
    ["Press Landmine a Dos Manos","Hombro","Barra","Deltoide anterior, tríceps","c"],
    ["Z-Press Sentado en el Suelo con Barra","Hombro","Barra","Deltoide, core, tríceps","c"],
    ["Z-Press con Mancuernas","Hombro","Mancuernas","Deltoide, core","c"],
    ["Press Bradford con Barra","Hombro","Barra","Deltoide anterior/medio","c"],
    ["Press de Hombro con Kettlebells","Hombro","Kettlebell","Deltoide, tríceps, core","c"],
    ["Elevaciones Laterales Sentado con Mancuernas","Hombro","Mancuernas","Deltoide medio","a"],
    ["Elevaciones Laterales en Polea Baja por Detrás","Hombro","Polea","Deltoide medio","a"],
    ["Elevaciones Laterales Acostado de Lado","Hombro","Mancuernas","Deltoide medio","a"],
    ["Elevaciones Laterales en Máquina","Hombro","Máquina","Deltoide medio","a"],
    ["Elevaciones Laterales Inclinado hacia Adelante","Hombro","Mancuernas","Deltoide posterior/medio","a"],
    ["Elevaciones Laterales con Parciales Pesadas","Hombro","Mancuernas","Deltoide medio","a"],
    ["Elevaciones Frontales con Mancuernas Agarre Neutro","Hombro","Mancuernas","Deltoide anterior","a"],
    ["Elevaciones Frontales con Barra Recta","Hombro","Barra","Deltoide anterior","a"],
    ["Elevaciones Frontales con Disco","Hombro","Disco","Deltoide anterior","a"],
    ["Elevaciones Frontales en Polea con Cuerda","Hombro","Polea","Deltoide anterior","a"],
    ["Pájaros Apoyado en Banco Inclinado","Hombro","Mancuernas","Deltoide posterior","a"],
    ["Pájaros en Polea Alta Cruzada","Hombro","Polea","Deltoide posterior","a"],
    ["Pájaros en Polea Baja Unilateral","Hombro","Polea","Deltoide posterior","a"],
    ["Remo al Mentón con Barra Z","Hombro","Barra","Deltoide, trapecio","a"],
    ["Remo al Mentón con Mancuernas","Hombro","Mancuernas","Deltoide, trapecio","a"],
    ["Remo al Mentón en Polea Baja","Hombro","Polea","Deltoide, trapecio","a"],
    ["Remo Deltoide Posterior en Polea Alta (High Row)","Hombro","Polea","Deltoide posterior, trapecio","a"],
    ["Y-Raises en Banco Inclinado","Hombro","Mancuernas","Deltoide posterior, trapecio inferior","a"],
    ["T-Raises en Banco Inclinado","Hombro","Mancuernas","Deltoide posterior, romboides","a"],
    ["Around the World con Mancuernas","Hombro","Mancuernas","Deltoide (completo)","a"],
    ["Flexiones en Pino / Handstand Push-ups","Hombro","Peso corporal","Deltoide, tríceps","c"],
    ["Flexiones Pike en Suelo","Hombro","Peso corporal","Deltoide, tríceps","c"],
    ["Flexiones Pike con Pies Elevados","Hombro","Peso corporal","Deltoide, tríceps","c"],
    ["Cuban Press con Mancuernas","Hombro","Mancuernas","Manguito rotador, deltoide","a"],
    ["Rotación Externa de Hombro en Polea","Hombro","Polea","Manguito rotador","a"],
    ["Rotación Interna de Hombro en Polea","Hombro","Polea","Manguito rotador","a"],
    ["Face Pull a Una Mano en Polea","Hombro","Polea","Deltoide posterior","a"],
    ["Press Militar con Banda Elástica","Hombro","Banda","Deltoide, tríceps","c"],
    ["Elevación Lateral Isométrica Sostenida","Hombro","Mancuernas","Deltoide medio","a"],

    // ================= CUÁDRICEPS =================
    ["Sentadilla Trasera Barra Alta","Cuádriceps","Barra","Cuádriceps, glúteo, core","c"],
    ["Sentadilla Trasera Barra Baja (Low Bar)","Cuádriceps","Barra","Glúteo, cuádriceps, cadena posterior","c"],
    ["Sentadilla Frontal con Agarre Cruzado","Cuádriceps","Barra","Cuádriceps, core","c"],
    ["Sentadilla Goblet con Kettlebell","Cuádriceps","Kettlebell","Cuádriceps, glúteo, core","c"],
    ["Sentadilla Hack Invertida en Máquina","Cuádriceps","Máquina","Glúteo, femoral","c"],
    ["Sentadilla Hack con Barra por Detrás","Cuádriceps","Barra","Cuádriceps, glúteo","c"],
    ["Sentadilla Búlgara con Barra","Cuádriceps","Barra","Cuádriceps, glúteo","c"],
    ["Sentadilla Búlgara en Máquina Smith","Cuádriceps","Smith","Cuádriceps, glúteo","c"],
    ["Sentadilla Búlgara con Peso Corporal","Cuádriceps","Peso corporal","Cuádriceps, glúteo","c"],
    ["Prensa de Piernas Horizontal","Cuádriceps","Máquina","Cuádriceps, glúteo","c"],
    ["Prensa de Piernas Vertical","Cuádriceps","Máquina","Cuádriceps, glúteo","c"],
    ["Prensa de Piernas Unilateral","Cuádriceps","Máquina","Cuádriceps, glúteo","c"],
    ["Sentadilla Sissy en Banco Específico","Cuádriceps","Máquina","Cuádriceps (recto femoral)","a"],
    ["Extensiones de Cuádriceps Unilateral","Cuádriceps","Máquina","Cuádriceps","a"],
    ["Extensiones de Cuádriceps con Pausas Isométricas","Cuádriceps","Máquina","Cuádriceps","a"],
    ["Sentadilla en Máquina Smith","Cuádriceps","Smith","Cuádriceps, glúteo","c"],
    ["Sentadilla Belt en Máquina","Cuádriceps","Máquina","Cuádriceps, glúteo","c"],
    ["Sentadilla Zercher con Barra","Cuádriceps","Barra","Cuádriceps, glúteo, core","c"],
    ["Sentadilla Sumo con Barra","Cuádriceps","Barra","Cuádriceps, aductores, glúteo","c"],
    ["Sentadilla Sumo con Kettlebell","Cuádriceps","Kettlebell","Cuádriceps, aductores, glúteo","c"],
    ["Zancadas Caminando con Barra","Cuádriceps","Barra","Cuádriceps, glúteo","c"],
    ["Zancadas Estáticas Adelante con Mancuernas","Cuádriceps","Mancuernas","Cuádriceps, glúteo","c"],
    ["Zancadas Reverse Lunge","Cuádriceps","Mancuernas","Cuádriceps, glúteo","c"],
    ["Zancadas Estáticas con Barra","Cuádriceps","Barra","Cuádriceps, glúteo","c"],
    ["Zancadas en Máquina Smith","Cuádriceps","Smith","Cuádriceps, glúteo","c"],
    ["Zancadas Cruzadas / Curtsy Lunge","Cuádriceps","Mancuernas","Glúteo medio, cuádriceps","c"],
    ["Step-ups con Barra","Cuádriceps","Barra","Cuádriceps, glúteo","c"],
    ["Sentadilla Cosaca con Peso","Cuádriceps","Mancuernas","Cuádriceps, aductores, glúteo","c"],
    ["Sentadilla Pistol (Una Pierna)","Cuádriceps","Peso corporal","Cuádriceps, glúteo, core","c"],
    ["Sentadilla Pistol Asistida con TRX","Cuádriceps","Peso corporal","Cuádriceps, glúteo","c"],
    ["Sentadilla Jefferson con Barra","Cuádriceps","Barra","Cuádriceps, glúteo","c"],
    ["Sentadilla Anderson","Cuádriceps","Barra","Cuádriceps, glúteo","c"],
    ["Sentadilla Pin Squat","Cuádriceps","Barra","Cuádriceps, glúteo","c"],
    ["Sentadilla con Caja (Box Squat)","Cuádriceps","Barra","Glúteo, cuádriceps","c"],
    ["Sentadilla con Barra Safety (SSB)","Cuádriceps","Barra","Cuádriceps, glúteo, core","c"],
    ["Zancadas con Déficit","Cuádriceps","Mancuernas","Cuádriceps, glúteo","c"],
    ["Zancadas Pendulares","Cuádriceps","Mancuernas","Cuádriceps, glúteo","c"],
    ["Sentadilla Skater","Cuádriceps","Peso corporal","Cuádriceps, glúteo","c"],
    ["Sentadilla Landmine","Cuádriceps","Barra","Cuádriceps, glúteo","c"],
    ["Sentadilla Isométrica en Pared (Wall Sit)","Cuádriceps","Peso corporal","Cuádriceps","a"],
    ["Wall Sit con Disco en los Muslos","Cuádriceps","Disco","Cuádriceps","a"],

    // ================= FEMORAL =================
    ["Peso Muerto Rumano con Mancuernas","Femoral","Mancuernas","Femoral, glúteo","c"],
    ["Peso Muerto Piernas Rígidas con Barra","Femoral","Barra","Femoral, glúteo, espalda baja","c"],
    ["Peso Muerto Piernas Rígidas con Mancuernas","Femoral","Mancuernas","Femoral, glúteo","c"],
    ["Peso Muerto con Barra Trap / Hexagonal","Femoral","Barra","Femoral, glúteo, cuádriceps, trapecio","c"],
    ["Peso Muerto Deficitario","Femoral","Barra","Femoral, glúteo, espalda","c"],
    ["Peso Muerto con Pausas","Femoral","Barra","Femoral, glúteo, espalda","c"],
    ["Peso Muerto en Máquina Smith","Femoral","Smith","Femoral, glúteo","c"],
    ["Peso Muerto Unilateral a Una Pierna con Mancuerna","Femoral","Mancuernas","Femoral, glúteo, core","c"],
    ["Peso Muerto Unilateral con Kettlebell","Femoral","Kettlebell","Femoral, glúteo, core","c"],
    ["Curl Femoral Acostado Unilateral","Femoral","Máquina","Isquiotibiales","a"],
    ["Curl Femoral de Pie Unilateral","Femoral","Máquina","Isquiotibiales","a"],
    ["Curl Femoral con Mancuerna entre los Pies","Femoral","Mancuernas","Isquiotibiales","a"],
    ["Curl Nórdico (Nordic Hamstring)","Femoral","Peso corporal","Isquiotibiales","a"],
    ["Curl Femoral en Fitball","Femoral","Peso corporal","Isquiotibiales, glúteo","a"],
    ["Curl Femoral en TRX / Suspensión","Femoral","Peso corporal","Isquiotibiales, glúteo","a"],
    ["Good Morning para Isquios Semi-flexionado","Femoral","Barra","Femoral, glúteo","c"],
    ["Peso Muerto Snatch Grip","Femoral","Barra","Femoral, glúteo, trapecio, espalda","c"],
    ["Peso Muerto Rumano B-Stance","Femoral","Mancuernas","Femoral, glúteo","c"],
    ["Curl Femoral Sentado Unilateral","Femoral","Máquina","Isquiotibiales","a"],

    // ================= GLÚTEO =================
    ["Hip Thrust en Máquina Específica","Glúteo","Máquina","Glúteo mayor","c"],
    ["Hip Thrust en Máquina Smith","Glúteo","Smith","Glúteo mayor","c"],
    ["Hip Thrust Unilateral con Mancuerna","Glúteo","Mancuernas","Glúteo mayor","c"],
    ["Hip Thrust con Banda Elástica","Glúteo","Banda","Glúteo mayor, glúteo medio","a"],
    ["Puente de Glúteo en Suelo con Barra","Glúteo","Barra","Glúteo mayor","c"],
    ["Puente de Glúteo a Una Pierna","Glúteo","Peso corporal","Glúteo mayor","a"],
    ["Patada de Glúteo en Máquina Dedicada","Glúteo","Máquina","Glúteo mayor","a"],
    ["Patada de Glúteo en Cuadrupedia con Mancuerna","Glúteo","Mancuernas","Glúteo mayor","a"],
    ["Abducciones de Cadera Inclinado en Máquina","Glúteo","Máquina","Glúteo medio","a"],
    ["Abducciones de Cadera en Polea Baja de Pie","Glúteo","Polea","Glúteo medio","a"],
    ["Abducciones con Banda (Monster Walk)","Glúteo","Banda","Glúteo medio","a"],
    ["Aducciones de Cadera en Polea Baja de Pie","Glúteo","Polea","Aductores","a"],
    ["Frog Pumps para Glúteo","Glúteo","Peso corporal","Glúteo mayor","a"],
    ["Extensiones de Cadera Reverse Hyper","Glúteo","Máquina","Glúteo, femoral, espalda baja","a"],
    ["Hip Thrust B-Stance","Glúteo","Barra","Glúteo mayor","c"],
    ["Clamshells con Banda","Glúteo","Banda","Glúteo medio","a"],
    ["Patada de Glúteo Cruzada en Polea","Glúteo","Polea","Glúteo mayor, medio","a"],
    ["Zancada Lateral con Mancuerna","Glúteo","Mancuernas","Glúteo medio, aductores, cuádriceps","c"],
    ["Zancada Lateral con Barra","Glúteo","Barra","Glúteo medio, cuádriceps","c"],

    // ================= GEMELO =================
    ["Elevación de Talones en Prensa 45°","Gemelo","Máquina","Gastrocnemio, sóleo","a"],
    ["Elevación de Talones en Prensa Horizontal","Gemelo","Máquina","Gastrocnemio, sóleo","a"],
    ["Elevación de Talones en Máquina Smith","Gemelo","Smith","Gastrocnemio","a"],
    ["Elevación de Talones a Una Pierna con Mancuerna","Gemelo","Mancuernas","Gastrocnemio","a"],
    ["Elevación de Talones con Barra a la Espalda","Gemelo","Barra","Gastrocnemio","a"],
    ["Elevación de Talones Donkey en Máquina","Gemelo","Máquina","Gastrocnemio","a"],
    ["Elevación de Talones con Kettlebell","Gemelo","Kettlebell","Gastrocnemio","a"],
    ["Elevación de Talones en Escalón (Peso Corporal)","Gemelo","Peso corporal","Gastrocnemio, sóleo","a"],
    ["Elevación de Tibiales contra Pared","Gemelo","Peso corporal","Tibial anterior","a"],
    ["Elevación de Tibiales con Barra Tibialis","Gemelo","Barra","Tibial anterior","a"],
    ["Paseo sobre Puntas con Mancuernas","Gemelo","Mancuernas","Gastrocnemio, sóleo","a"],
    ["Elevación de Talones en Máquina Hack","Gemelo","Máquina","Gastrocnemio","a"],
    ["Elevación de Talones con Pies hacia Adentro","Gemelo","Máquina","Gastrocnemio (externo)","a"],
    ["Elevación de Talones con Pies hacia Afuera","Gemelo","Máquina","Gastrocnemio (interno)","a"],

    // ================= BÍCEPS / BRAQUIAL =================
    ["Curl de Bíceps con Barra Z","Bíceps","Barra","Bíceps braquial","a"],
    ["Curl Simultáneo con Mancuernas","Bíceps","Mancuernas","Bíceps braquial","a"],
    ["Curl Martillo Alterno con Mancuernas","Bíceps","Mancuernas","Braquial, braquiorradial","a"],
    ["Curl Martillo Cruzado (Pinwheel)","Bíceps","Mancuernas","Braquial, braquiorradial","a"],
    ["Curl en Banco Scott con Barra Z","Bíceps","Barra","Bíceps (cabeza corta)","a"],
    ["Curl en Banco Scott con Barra Recta","Bíceps","Barra","Bíceps (cabeza corta)","a"],
    ["Curl en Banco Scott con Mancuerna Unilateral","Bíceps","Mancuernas","Bíceps","a"],
    ["Curl en Banco Scott en Máquina","Bíceps","Máquina","Bíceps","a"],
    ["Curl de Bíceps en Polea Baja con Barra Recta","Bíceps","Polea","Bíceps braquial","a"],
    ["Curl de Bíceps en Polea Baja con Barra Z","Bíceps","Polea","Bíceps braquial","a"],
    ["Curl Martillo en Polea con Cuerda","Bíceps","Polea","Braquial, braquiorradial","a"],
    ["Curl Araña con Barra Z","Bíceps","Barra","Bíceps (cabeza corta)","a"],
    ["Curl 21 con Barra Z","Bíceps","Barra","Bíceps braquial","a"],
    ["Curl Bayesian Unilateral en Polea","Bíceps","Polea","Bíceps (cabeza larga)","a"],
    ["Curl Tumbado en Polea Alta","Bíceps","Polea","Bíceps (cabeza larga)","a"],
    ["Curl Hércules en Poleas Altas","Bíceps","Polea","Bíceps braquial","a"],
    ["Curl Drag con Barra","Bíceps","Barra","Bíceps braquial","a"],
    ["Curl Drag con Mancuernas","Bíceps","Mancuernas","Bíceps braquial","a"],
    ["Curl Zottman con Mancuernas","Bíceps","Mancuernas","Bíceps, braquiorradial, antebrazo","a"],
    ["Curl Zottman en Banco Predicador","Bíceps","Mancuernas","Bíceps, antebrazo","a"],
    ["Curl de Bíceps Invertido con Barra Z","Antebrazo","Barra","Braquiorradial, antebrazo","a"],
    ["Curl de Bíceps en Barra Landmine","Bíceps","Barra","Bíceps braquial","a"],
    ["Curl Martillo en Polea con Barra Recta","Bíceps","Polea","Braquial, braquiorradial","a"],
    ["Curl con Barra Olímpica a Una Mano","Bíceps","Barra","Bíceps braquial","a"],
    ["Curl Inclinado Martillo con Mancuernas","Bíceps","Mancuernas","Braquial, bíceps (cabeza larga)","a"],
    ["Curl de Bíceps con Toalla y Disco","Bíceps","Disco","Bíceps, agarre","a"],
    ["Curl de Bíceps en Máquina de Cables Sentado","Bíceps","Máquina","Bíceps braquial","a"],
    ["Curl con Disco a Dos Manos","Bíceps","Disco","Bíceps, antebrazo","a"],
    ["Curl Isométrico en Banco Predicador","Bíceps","Barra","Bíceps braquial","a"],
    ["Curl con Fat Gripz (Agarre Grueso)","Bíceps","Mancuernas","Bíceps, antebrazo, agarre","a"],

    // ================= TRÍCEPS =================
    ["Press Francés Acostado con Barra Recta","Tríceps","Barra","Tríceps (cabeza larga)","a"],
    ["Press Francés en Banco Inclinado con Barra Z","Tríceps","Barra","Tríceps (cabeza larga)","a"],
    ["Press Francés en Banco Declinado con Barra Z","Tríceps","Barra","Tríceps","a"],
    ["Press Francés con Mancuernas Acostado","Tríceps","Mancuernas","Tríceps","a"],
    ["Extensiones de Tríceps en Polea con Barra V","Tríceps","Polea","Tríceps","a"],
    ["Extensiones de Tríceps en Polea Agarre Supino","Tríceps","Polea","Tríceps (cabeza medial)","a"],
    ["Extensiones de Tríceps Unilaterales en Polea","Tríceps","Polea","Tríceps","a"],
    ["Extensiones sobre la Cabeza con Mancuerna a Dos Manos","Tríceps","Mancuernas","Tríceps (cabeza larga)","a"],
    ["Extensiones sobre la Cabeza en Polea con Cuerda","Tríceps","Polea","Tríceps (cabeza larga)","a"],
    ["Extensiones Katana Cruzadas en Polea","Tríceps","Polea","Tríceps (cabeza larga)","a"],
    ["Fondos en Máquina de Tríceps","Tríceps","Máquina","Tríceps","c"],
    ["Patada de Tríceps Unilateral en Polea","Tríceps","Polea","Tríceps","a"],
    ["Press Tate con Mancuernas","Tríceps","Mancuernas","Tríceps","a"],
    ["Press JM con Barra","Tríceps","Barra","Tríceps","c"],
    ["Flexiones Diamante Inclinadas","Tríceps","Peso corporal","Tríceps, pectoral interno","c"],
    ["Extensiones de Tríceps en Suelo (Peso Corporal)","Tríceps","Peso corporal","Tríceps","c"],
    ["Extensiones sobre la Cabeza con Barra Z de Pie","Tríceps","Barra","Tríceps (cabeza larga)","a"],
    ["Extensiones de Tríceps en Máquina de Palanca","Tríceps","Máquina","Tríceps","a"],
    ["Press de Banca Agarre Cerrado en Máquina Smith","Tríceps","Smith","Tríceps, pectoral interno","c"],
    ["Press de Banca Declinado Agarre Cerrado","Tríceps","Barra","Tríceps, pectoral inferior","c"],
    ["Extensiones sobre la Cabeza en Banco Inclinado con Mancuernas","Tríceps","Mancuernas","Tríceps (cabeza larga)","a"],
    ["California Press","Tríceps","Barra","Tríceps, pectoral","c"],
    ["Press de Tríceps en Máquina Selectorizada","Tríceps","Máquina","Tríceps","a"],

    // ================= ANTEBRAZO / AGARRE =================
    ["Curl de Muñeca en Supinación con Barra","Antebrazo","Barra","Flexores del antebrazo","a"],
    ["Curl de Muñeca en Pronación con Barra","Antebrazo","Barra","Extensores del antebrazo","a"],
    ["Curl de Muñeca con Mancuernas en Banco","Antebrazo","Mancuernas","Flexores del antebrazo","a"],
    ["Curl de Muñeca Invertido con Mancuernas","Antebrazo","Mancuernas","Extensores del antebrazo","a"],
    ["Paseo del Granjero con Mancuernas","Antebrazo","Mancuernas","Agarre, antebrazo, trapecio, core","c"],
    ["Paseo del Granjero con Barra Trap","Antebrazo","Barra","Agarre, antebrazo, trapecio","c"],
    ["Rollo de Muñeca con Disco (Wrist Roller)","Antebrazo","Disco","Antebrazo, agarre","a"],
    ["Colgado en Barra a Dos Manos (Dead Hang)","Antebrazo","Peso corporal","Agarre, antebrazo","a"],
    ["Pinza de Discos (Pinch Grip)","Antebrazo","Disco","Agarre, antebrazo","a"],
    ["Curl de Muñeca en Polea Baja","Antebrazo","Polea","Flexores del antebrazo","a"],
    ["Cierre de Hand Grippers","Antebrazo","Banda","Agarre, antebrazo","a"],
    ["Curl de Muñeca Unilateral con Mancuerna","Antebrazo","Mancuernas","Flexores del antebrazo","a"],
    ["Sostén de Barra Olímpica por un Extremo","Antebrazo","Barra","Agarre, antebrazo","a"],

    // ================= CORE / ABDOMEN =================
    ["Crunch Abdominal con Disco en el Pecho","Core","Disco","Recto abdominal","a"],
    ["Crunch en Máquina Abdominal","Core","Máquina","Recto abdominal","a"],
    ["Crunch en Fitball","Core","Peso corporal","Recto abdominal","a"],
    ["Crunch Declinado en Banco","Core","Peso corporal","Recto abdominal","a"],
    ["Crunch Declinado con Peso","Core","Disco","Recto abdominal","a"],
    ["Elevaciones de Rodillas Colgado","Core","Peso corporal","Abdomen inferior, flexores de cadera","a"],
    ["Elevaciones de Piernas en Silla Romana","Core","Peso corporal","Abdomen inferior","a"],
    ["Elevaciones de Piernas Acostado","Core","Peso corporal","Abdomen inferior","a"],
    ["Toes-to-Bar (Pies a la Barra)","Core","Peso corporal","Abdomen, flexores de cadera","c"],
    ["Plancha con Disco en la Espalda","Core","Disco","Core","a"],
    ["Plancha Lateral con Elevación de Cadera","Core","Peso corporal","Oblicuos, core","a"],
    ["Rueda Abdominal de Rodillas","Core","Peso corporal","Core, recto abdominal","c"],
    ["Twist Ruso con Balón Medicinal","Core","Peso corporal","Oblicuos, core","a"],
    ["Leñador en Polea Baja","Core","Polea","Oblicuos, core","a"],
    ["Deadbug con Fitball","Core","Peso corporal","Core profundo, transverso","a"],
    ["Vacío Abdominal (Stomach Vacuum)","Core","Peso corporal","Transverso abdominal","a"],
    ["Press Pallof en Polea de Pie","Core","Polea","Core (antirrotación), oblicuos","a"],
    ["Press Pallof Arrodillado","Core","Polea","Core (antirrotación)","a"],
    ["Paseo del Granjero Unilateral (Suitcase Carry)","Core","Mancuernas","Oblicuos, core, agarre","c"]
  ];

  var existe = {};
  EJS.forEach(function (e) { existe[normEx(e.n)] = true; });
  L.forEach(function (r) {
    var n = r[0];
    if (existe[normEx(n)]) return;
    EJS.push({ n: n, g: r[1], e: r[2], m: r[3], t: r[4] });
    existe[normEx(n)] = true;
  });
})();
